### ISSUE TITLE
Atomic operations.

### ISSUE THREAD

**Issue by rmedaer** [Slidesk/libdploy#9]
## Issue
Currently, `libdploy` expose "non-atomic" operations. For example, if we would like to update host variables, `libdploy` will write a file and commit it :

```
    return self.read()
    .then(function(config) {
        config[0].vars = variables;
        return self.write(config);
    })

    .then(function() {
        return self.commit('cluster.host.variables');
    });
```

This operation could be broken if two clients modify (pseudo-)simultaneously variables...

  1. Client **1**: Write config `{"value": "123456789"}`.
  2. Client **2**: Write config `{"value": "failure in approach"}`.
  3. Client **2**: Commit changes.
  4. Client **1**: Commit changes.

The result will be `{"value": "failure in approach"}` with client **1** as author instead of client **2**. Furthermore an empty commit will probably fail with client **2** as author.

## Outcome
Implements a lock system to avoid this issue. Think about parallel processes...
Current ideas:

  * read/write lock
  * mutex/semaphore
  * redis

**Comment by rmedaer** [comment]
I implemented it with Redis and a singleton in d166e8c and 97a9da0. We should be able to select the lock system (e.g. Redis, FS lock, SHM).

As discussed with  @adaxi, let's implement that before pull in develop branch.

**Comment by rmedaer** [comment]
Commits 2804a83 & 9cf3b44 should close the story. Let's merge all of this.

**Comment by rmedaer** [comment]
@adaxi , would you like to write a "system lock" before closing this story ?

**Comment by adaxi** [comment]
Yes, I'll do that! I will try to do it this week.

**Comment by rmedaer** [comment]
A FS lock system has been added by  @adaxi  in #13 . However, I let this issue open until improvements made by @matthieusieben in Lock to avoid finally clause.
